/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useEffect} from 'react';

import RobustWs from 'react-native-robust-ws';

export default function App() {
    useEffect(() => {
        let cnt = 0;
        console.log(RobustWs);
        const ws = new RobustWs("ws://localhost:8765");

        const session = ws.openSession({
            onMessage: (m) => {
                cnt++;
                console.log(m);
            },
        });

        session.send("1");
        session.send("2");
        session.send("3");
    }, []);

    return null;
}
